baseURL = 'https://alchg.github.io/'
languageCode = 'ja'
defaultContentLanguage = 'ja'
title = 'Alchg Projects'
theme = 'simple-multipage'
publishDir = 'docs'


[params]
twitter_user = '@marimo_linux'
blog_title = '銀の棲家'

[taxonomies]
tag = 'tags'
category = 'categorise'
