baseURL = 'https://alchg.github.io/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'simple-multipage'
publishDir = 'docs'


[params]
twitter_user = '@sample'
blog_title = 'Sample Blog'

[taxonomies]
tag = 'tags'
category = 'categorise'
