baseURL = 'https://alchg.github.io/'
languageCode = 'ja'
defaultContentLanguage = 'ja'
title = 'Alchg Projects'
theme = 'simple-multipage'
publishDir = 'docs'

DefaultContentLanguage = "ja"

[languages]
 [languages.ja]
  weight = 10
  title = "Alchg Projects"
 [languages.en]
  weight = 20
  title = "Alchg Projects"



[params]
x_user = '@marimo_linux'
blog_title = '銀の棲家'

[taxonomies]
tag = 'tags'
category = 'categorise'
